name: K6 Performance Test

on:
  push:
    branches: [ main, master ]

jobs:
  k6_test:
    name: Run k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Instalamos k6 manualmente (es muy rápido)
      - name: Instalar k6
        run: |
          curl -s https://dl.k6.io/key.gpg | sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --import
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      # 2. Corremos k6 directamente usando el Chrome que ya tiene Ubuntu
      - name: Ejecutar k6 browser test
        run: |
          k6 run scripts/07_k6_browser.js
        env:
          K6_BROWSER_EXECUTABLE_PATH: /usr/bin/google-chrome

      - name: Subir Reporte HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: k6-report
          path: summary.html